import { ReduxProvider } from "@/lib/reduxProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Header from "@/components/layout/Header";

const roboto = Roboto({ weight: ["100", "300", "400", "500", "700", "900"], subsets:["latin"] });

export const metadata: Metadata = {
  title: "Todo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={`${roboto.className} p-6`}>
          <Header />
          {children}
        </body>
      </html>
    </ReduxProvider>
  );
}
